### ISSUE TITLE
Meson installation fails

### ISSUE THREAD

**Issue by Kazhnuz** [Ubuntu/communitheme-sounds#1]
Meson fails to install the "communitheme-sounds" directory into usr/share/sounds. That's because the line 8 of meson.build try to look to a folder named "communitheme" while the folder is called "communitheme-sounds".

The solution would either to rename the sound theme folder to "communitheme" instead of communitheme-sounds (and changing the line 1 of the meson.build), or to change that line to communitheme-sounds (and changing the instructions too).

**Comment by merlijn-sebrechts** [comment]
Good catch! Fixed it. :butterfly:
